---
- name: Install necessary stuff
  hosts: all
  tasks: 
  - name: Install stuff
    dnf:
      name: 
        - python3-pip
        - epel-release
        - python3-devel
        - gcc
      state: latest
  - name: Install stuff
    dnf:
      name: 
        - ansible
      state: latest
  - name: Install pip dependencies
    pip:
      name: 
        - ansible-runner
        - pywinrm
